### ISSUE TITLE
How to start isn't clear enough

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#7]
The instructions on how to get an L project started are not clear.

So, for instance, I want to get started, so I copy the sample_app folder to where I am going to have my project, because I want the folder and file structure that goes with it.  I open the standalone.livecode stack.  The behavior for that stack is expecting the  framework to be in a framework subfolder, instead of wherever I have the framework stashed (in my git folder).  I have to reassign the behavior, then quit LC and restart.

Unfortunately, doing that doesn't help me, because clicking on the "Open application" doesn't do what you would expect if you hit the button with the full L folder structure in place.

After reading the "An example" section, things get muddier - in there, you seem to suggest that the folder structure should be different than the way you have the L folder and/or the sample_app folder laid out.  For example, the "An example" section suggests that the L folder should be at the same level as the standalone.livecode file, but that isn't the way it's laid out in the repository.

Some explanation as to why the "sample app standalone" opens the "my app" stack would be good.

It would be good to have the other folders added to the sample so the developer has structure already in place (helpers/frontscripts/backscripts/behaviors/etc.)

I know you are used to the jargon being a certain way, but perhaps some different names would be better - "UI", or "dialogs" instead of "components", for example.

LoadBehavior - why would I want an SOS to set its own behavior?  Is this so a behavior can set its parent behavior?

**Comment by trevordevore** [comment]
@macMikey 

- The sample app folder included in the framework repository can't be laid out as suggested in the "An example" section because it would require duplicating the framework folder. That wouldn't make sense. It probably makes the most sense to move the sample app out of the repository. Maybe it is included in the wiki area with a detailed walkthrough. The bigger problem is coming up with a sample application to build. Suggestions welcome. The framework probably needs a command or utility stack that creates a new application in a specified folder as well.

- Why does the sample app open "my app"? It has to open something :-)

- I'm open to name suggestions. "ui" could work for components. I don't think "dialogs" does as "dialogs" are a subset of a ui stack. "components" are any stacks with a UI. I chose "helpers" instead of "plugins" because I didn't want people confusing "plugins" used for the IDE with "plugins" used in a Levure app.

- LoadBehavior - necessary for chained behaviors if you want the logic to be self contained. Since you can't set any properties of a script only stack you can't set the behavior of it. Another script has to do it UNLESS you send a message to the stack script when it is loaded.

**Comment by macMikey** [comment]
Since I'm trying to get started writing my first levure project, anyway, I'll try to think of a good example app to build.
The utility stack is part of what I was thinking about with the other pull request for building/configuring the app.yml file

I understand that you mean more than just "ui" for components, but then I have to wonder, if components are libraries and front and backscripts, then why have libraries, frontscripts, and backscripts separate?  If I read the wiki right, you can have libraries in libraries, but also in components.  That seems like a bad idea.  If you want to let the user have libraries/frontscripts/backscripts in components, then at least tell them that the libraries/fronscripts/backscripts should be for the components, only, not for the main project, OR, get rid of the top level libraries/frontscripts/backscripts and put everything in components.

I like keeping it simple, so switching "components" to "UI" would do just that.  I don't have an idea for "helpers", yet, but "helpers" isn't helpful when you're trying to shift from the LC stack paradigm to this one.

**Comment by macMikey** [comment]
This is being addressed daily with the wiki, so I'm closing it.
