### ISSUE TITLE
Packager Docs Are Not Clear

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#77]
I'm reading through the packager, and I am confused
https://github.com/trevordevore/levure/wiki/packager

### Configure the copy files section of the app.yml file.
I don't see a good description in this article as to what or why.  The closest I could find was https://github.com/trevordevore/levure/wiki/How-do-I-include-additional-files-and-folders-in-my-application-builds%3F
which is referenced further down the page, BUT that is not really clear, either.  THAT page refers to copying "Additional" files, such as database files - but
a) In order to run the app interpreted, I have to already have access to those files, and in other places in the wiki, it is suggested that those files be located in certain Levure folders, e.g. resources (and perhaps assets, but assets are not well-defined, yet).
b) It is implied, I guess, but it isn't obvious, that you have to make reference to those folders in the copy files section of the app.yml file.
c) Why doesn't Levure by default copy everything in the app folder?  Which files/folders are auto-copied, and which ones are not?

**Comment by trevordevore** [comment]
> a) In order to run the app interpreted, I have to already have access to those files, and in other places in the wiki, it is suggested that those files be located in certain Levure folders, e.g. resources (and perhaps assets, but assets are not well-defined, yet).

In the current version of the `app.yml` file that is created for new apps the `assets` folder is automatically added to `build profiles` > `all profiles` > `copy files` > `all platforms` so anything in assets will be copied over.

`resources` is no longer used as it causes problems when building for ios. It has been replaced by `assets`. `assets` is just a folder where you put non-stack files that your app relies on.

> b) It is implied, I guess, but it isn't obvious, that you have to make reference to those folders in the copy files section of the app.yml file.

I've updated the docs and added more details about what is copied over by default.

> c) Why doesn't Levure by default copy everything in the app folder? Which files/folders are auto-copied, and which ones are not?

Because not all files apply to all platforms. For example, an app can have some files that are for macOS only and others that are for Windows only. The docs now mention which files are automatically (`ui`, `libraries`, `frontscripts`, `backscripts`, and `helpers`)

**Comment by trevordevore** [comment]
Actually `behaviors` are automatically packaged. I left it out originally but I've just updated the docs. While `assets` isn't automatically copied unless an entry is made in a `copy files` section, there is a `copy files` entry for `assets` in the `app.yml` file that the app creator stack creates.
