### ISSUE TITLE
Trouble setting application data folder on Android

### ISSUE THREAD

**Issue by jim1001** [trevordevore/levure#91]
Was having some trouble setting an application data folder on Android. To test I created a fresh sample Levure project & made the minimum of changes.

This gives "error while initializing app (unable to create folder /data/user/0/files/Application Support: can’t create that directory)".

If there is a value set for the default shared application data folder then this throws a different error on Android. Can post the project if any help.

Also on [this wiki page](https://github.com/trevordevore/levure/wiki/How-do-I-configure-my-application-data-storage-locations%3F) it says the application data folder for Android is 

> ~/Documents/Application Support/com.mycompany.myapplication

I couldn't find this on my Android device & I''ve read there aren't user home directories on Android.

Thanks.

**Comment by spencerlearning** [comment]
On Android, Levure automatically creates an `Application Support` folder in the `Documents` folder for the app. The application data folder for your app is created within the Application Support folder using the name defined by your `application data folder` setting in the `app.yml` file.

So if your `app.yml` setting looks like this:

```
# app.yml

application data folder:
  user:
    android: myAppName
```

Your application data folder will be `~/Documents/Application Support/myAppName`, where `~` is used to represent your app root.

**Do not use the bundle identifier** (com.mycompany.myapplication) for the Android `application data folder` setting. This may cause an error. You cannot leave the setting blank, so use anything but the bundle identifier (I will be changing the example in the Wiki).

When writing your app, you will always get the path to the application data folder with [levureApplicationDataFolder](https://github.com/trevordevore/levure/wiki/Levure-API#levureApplicationDataFolder) so once it is set up you don't need remember the details.

@jim1001 - Are you able to get it working on Android now?

**Comment by jim1001** [comment]
Brian,

Yes, got it working with your help - thank you.

I'm used to the ~ character representing the user home directory. I put the folder name under user : android as you specified above and didn't use the bundle identifier. I also checked that the same folder name worked under user : default & it did.

Other points / questions:

- Why there can be a user folder but not a shared one for Android?
- Does the folder & prefs file persist when the app closes?
- levureApplicationDataFolder() returned /data/user/0/org.uom.adft/files/Application Support/adfu1 where org.uom.adft was the app bundle name & adfu was the application data folder I specified in app.yml. Is that an alias to the path you mentioned above?

Best wishes,
Jim

**Comment by jim1001** [comment]
> Does the folder & prefs file persist when the app closes?

I mean I'm pretty sure they do otherwise users wouldn't be too happy, but just seeking confirmation...

**Comment by jim1001** [comment]
> Do the folder & prefs file persist when the app closes?

I've tested this and verified that preferences are saved between app sessions. I'd still like to find the folder on the Android filesystem so I can remove it as an easy way of resetting preferences outside the app. It doesn't appear on file browsers I have although I'm still a bit unsure of the path with aliases etc.

I was also having a problem using prefsSave of the Preferences helper. I was calling it from command PreShutdownApplication of app.livecodescript since I thought this was called automatically when the app is closed. Am I mistaken? It doesn’t seem to be executed when I close the app.

Thanks.

**Comment by spencerlearning** [comment]
@jim1001 ,

Here are some answers to your questions:

_Why there can be a user folder but not a shared one for Android?_

On Android, apps are isolated and sandboxed similar to iOS so there are no shared folders like you have in macOS and Windows.

_Does the folder & prefs file persist when the app closes?_

Yes. Regarding preferences, Levure automatically saves the preferences file right before shutdown. Levure does _not_ automatically save preferences whenever you set or change a preference, it only saves before shutdown. You can force preferences to be saved at any time using [prefsSave](https://github.com/trevordevore/levure/wiki/helper-preferences#prefsSave).

_levureApplicationDataFolder() returned /data/user/0/org.uom.adft/files/Application Support/adfu1 where org.uom.adft was the app bundle name & adfu was the application data folder I specified in app.yml. Is that an alias to the path you mentioned above?_

Yes. On Android, Levure uses the LiveCode function `specialFolderPath("documents")` to get the path to the Documents folder for your app. In your case, `specialFolderPath("documents")` should return something like `/data/user/0/org.uom.adft/files` but you do not need to know the gory path details other than to satisfy your curiosity.

In practice, you will use `specialFolderPath("documents")` to get the path to the Documents folder which is where your app is able to write and store folders and files on Android. And you will use `levureApplicationDataFolder()` to get the path to your application data folder within the Documents folder. Again, you do not need to know the path details, you simply trust that those functions return the correct path and then append your specific file and folder names onto that path.

_I've tested this and verified that preferences are saved between app sessions. I'd still like to find the folder on the Android filesystem so I can remove it as an easy way of resetting preferences outside the app. It doesn't appear on file browsers I have although I'm still a bit unsure of the path with aliases etc._

You can remove the preferences file in Levure using the [prefsGetPreferenceFile](https://github.com/trevordevore/levure/wiki/helper-preferences#prefsGetPreferenceFile) function like this:

```
delete file prefsGetPreferenceFile("user")
```

_I was also having a problem using prefsSave of the Preferences helper. I was calling it from command PreShutdownApplication of app.livecodescript since I thought this was called automatically when the app is closed. Am I mistaken? It doesn’t seem to be executed when I close the app._

Levure calls `prefsSave` automatically right before shutdown, so you shouldn't need to call it again in `preShutDownApplication`.

**Comment by jim1001** [comment]
Brian,

Thanks for your time going over these.

> _On Android, apps are isolated and sandboxed similar to iOS so there are no shared folders like you have in macOS and Windows._


To be clear, the terms  shared and user are to do with user accounts aren’t they?

> _Levure automatically saves the preferences file right before shutdown._


Would be useful to document that in the wiki command description (I know the wiki is evolving all the time & already holds a wealth of well-written useful information). The save didn’t seem to happen for me but could have been some other problem preventing it. Where is the code for it? I couldn’t find a prefsSave in app.livecodescript. Is it done some other way?

> _but you do not need to know the gory path details other than to satisfy your curiosity._


As I said, in my case  it *would* be handy to know so I can delete the preferences file outside LiveCode. I will be setting up some devices to give to users for a trial. I intend to  personally install the app & try it. When finished I could just remove any set preferences by deleting the file.  A workaround could be to include a “Reset preferences” button in the app to set them all to empty or to default values using the Helper preferences API.

Many thanks again!

**Comment by trevordevore** [comment]
@jim1001 

> To be clear, the terms shared and user are to do with user accounts aren’t they?

Yes. "user" is the current user using the app. "shared" is available to all users. "shared" is not available on mobile.

> The save didn’t seem to happen for me but could have been some other problem preventing it. Where is the code for it? I couldn’t find a prefsSave in app.livecodescript. Is it done some other way?

Look at the `levureShutdownApplication` command in `levure.livecodescript`. It calls `prefsSave`. `levureShutdownApplication` isn't called while working in the IDE. Only in a standalone.

**Comment by trevordevore** [comment]
@jim1001 I've updated the wiki page for preferences.

https://github.com/trevordevore/levure/wiki/Helper-preferences#saving-preferences
