### ISSUE TITLE
Wiki: Describe how to wire the default stack that opens (feature request)

### ISSUE THREAD

**Issue by chstrong** [trevordevore/levure#93]
Hi Trevor,

Great Framework you have put together. Looks fantastic. I'm currently testing it and thought, I'll just let you know where I struggled a little, so it might help you to extend your documentation.

It was really easy to follow the tutorial and the videos. I created a first ui stack, created the behaviour and it worked as described. 

It took me not long, but a while to discover how I can change the default stack that is loaded, when opening the application. I struggled at first to figure out, that this has to be done in the app.livecodescript file.

It would be more clear to the users, if there would be a hint in the standalone.livecode Wiki page and the app.livecodescript Wiki page, how to define the default stack that is loaded. 

I was first checking if I can find this information in the standalone.livecode page and then on the app.yml page (because I thought it might be a configuration option) and then on the app.livecodescript page. I needed to open the app.livecodescript file, to find it.

Cheers,
Chris

**Comment by trevordevore** [comment]
@chstrong Thanks for the feedback. I added a note to the Getting Started page `Loading an Application in the LiveCode IDE`. Look at step [2]:

https://github.com/trevordevore/levure/wiki/Loading-an-Application-in-the-LiveCode-IDE

That seems like a good location to mention where to change the UI stack that opens as you are going through the process of creating your first app. I also added a note to the `standalone.livecode` page that tells you where you can change what happens when the app loads. 

The `application.livecodescript` page already mentions that `OpenApplication` is where you change the UI stack that loads but I can see how that would be easy to miss.

**Comment by chstrong** [comment]
Hi Trevor, thanks. Looks better now.

In the app.livecodescript page would it make sense to change the text to following below in the OpenApplication section? I'll leave that up to you.

The OpenApplication handler is called after InitializeApplication. This is where you open your "default" UI stack when the application launches.

**Comment by trevordevore** [comment]
Good suggestion. I clarified it a bit further with this:

> The `OpenApplication` handler is called after `InitializeApplication`. This is where you open the UI stack that will be presented to the end user first.
